version: "3.3"

services:
    ttt-api:
        build: .
        image: ttt-api
        container_name: ttt-api
        env_file: .env

networks:
    default:
        external:
            name: cluster
