version: "3.3"

services:
    ttt-api:
        build: .
        image: ttt-api
        container_name: ttt-api
        ports:
            - "7000:8080"

networks:
    default:
        external:
            name: cluster
